baseurl = "http://blog.wordadoplicus.com/"
languageCode = "en-us"
title = "Whispers of Dinotechture"
subtitle = " of Dinotechture"

[params]
  GoogleAnalyticsUserID  = "bobby" # optional
  Author = "Shekhar Gulati"
  Subtitle = "A blog on Implementeing Wordadoplicus.com"
