baseurl = "http://blog.wordadoplicus.com/"
copyright = "&copy; 2016 Wordadoplicus LLC"
languageCode = "en-us"
title = "Whispers of Dinotechture"

[params]
  GoogleAnalyticsUserID  = "bobby" # optional
  Author = "Daniel Eklund"
  Subtitle = "A blog on Implementing Wordadoplicus.com"
